plugins {
    id "dev.architectury.loom" version "1.11-SNAPSHOT"
}

version = "1.0.0"

loom {
    forge {
        mixinConfigs = ["catnipfix.mixins.json"]
    }
}

repositories {
    maven { url = "https://maven.createmod.net" }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	forge "net.minecraftforge:forge:${project.forge_version}"
    modCompileOnly "net.createmod.ponder:Ponder-Forge-1.20.1:1.0.92"

    modImplementation(files("libs/create-1.20.1-6.0.8.jar"))
    modImplementation(files("libs/flywheel-forge-1.20.1-1.0.5.jar"))
    modImplementation(files("libs/mixinextras-forge-0.4.1.jar"))
    modImplementation(files("libs/Ponder-Forge-1.20.1-1.0.91.jar"))
    modImplementation(files("libs/Registrate-MC1.20-1.3.3.jar"))
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
    it.options.encoding = "UTF-8"
}
